const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

// get the constants for currency
const { CURRENCY_RATES, CURRENCY_SYMBOLS } = require("../constants/currency.constants");



const generateMonthlyReport = (expenses, month) => {

  return new Promise((resolve, reject) => {

    const dirPath = path.join(__dirname, "../reports");

    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }

    const filePath = path.join(dirPath, `report-${Date.now()}.pdf`);

    const doc = new PDFDocument({
      margin: 50,
      size: "A4"
    });

    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    /* =========================
       HEADER
    ========================= */

    doc
      .fontSize(22)
      .fillColor("#2c3e50")
      .text("Expense Tracker Ltd.", 50, 50);

    doc
      .fontSize(10)
      .fillColor("#7f8c8d")
      .text("123 Business Street, DHA Phase 6, Lahore", 50, 75);

    doc.moveTo(50, 95).lineTo(550, 95).stroke("#cccccc");

    /* =========================
       REPORT INFO
    ========================= */

    doc.moveDown(2);

    doc
      .fontSize(16)
      .fillColor("#333")
      .text(`Monthly Expense Report — ${month}`, { underline: true });

    doc
      .fontSize(10)
      .text(`Generated on: ${new Date().toDateString()}`, {
        align: "right"
      });

    /* =========================
       TABLE CONFIG
    ========================= */

    const tableTop = 170;
    const rowHeight = 25;

    const idX = 60;
    const descX = 120;
    const amountX = 450;

    let y = tableTop;

    const drawTableHeader = () => {

      doc
        .rect(50, y, 500, 25)
        .fill("#34495e");

      doc
        .fillColor("#ffffff")
        .font("Helvetica-Bold")
        .fontSize(11);

      doc.text("ID", idX, y + 7);
      doc.text("Description", descX, y + 7);
      doc.text("Amount", amountX, y + 7);

      y += 30;

      doc
        .font("Helvetica")
        .fillColor("#333");
    };

    drawTableHeader();

    /* =========================
       TABLE ROWS WITH PAGINATION
    ========================= */

    const maxY = doc.page.height - 150;
    let total = 0;

    expenses.forEach((expense, index) => {

      if (y > maxY) {

        doc.addPage();

        y = 80;

        drawTableHeader();
      }
      const isPkrMatch = expense.defaultCurrency === CURRENCY_SYMBOLS.PKR && expense.currency === CURRENCY_SYMBOLS.PKR;
      const isUsdMatch = expense.defaultCurrency === CURRENCY_SYMBOLS.USD && expense.currency === CURRENCY_SYMBOLS.USD;

      if(isPkrMatch || isUsdMatch){
            total += expense.amount;
      }else if(expense.defaultCurrency === CURRENCY_SYMBOLS.PKR && expense.currency === CURRENCY_SYMBOLS.USD){
            const dollarToPkr = expense.amount * CURRENCY_RATES.USD_TO_PKR;
            total+=dollarToPkr
      }else if(expense.defaultCurrency === CURRENCY_SYMBOLS.USD && expense.currency === CURRENCY_SYMBOLS.PKR){
            const pkrToDollar = expense.amount * CURRENCY_RATES.PKR_TO_USD;
            total+=pkrToDollar;
      }
     
      // Zebra row background
      if (index % 2 === 0) {
        doc
          .rect(50, y - 5, 500, 25)
          .fill("#f7f7f7")
          .fillColor("#333");
      }

      doc.text(index + 1, idX, y);
      doc.text(expense.title, descX, y);

      doc.text(
        `${expense.currency} ${expense.amount.toFixed(2)}`,
        amountX,
        y
      );

      y += rowHeight;
    });

    /* =========================
       SUMMARY SECTION
    ========================= */

    const avg = expenses.length ? total / expenses.length : 0;

    if (y > doc.page.height - 120) {
      doc.addPage();
      y = 100;
    }

    const summaryY = y + 20;

    doc
      .moveTo(50, summaryY)
      .lineTo(550, summaryY)
      .stroke("#2980b9");

    doc
      .font("Helvetica-Bold")
      .fontSize(12);

    doc.text(`Total Expenses: ${expenses[0].defaultCurrency === CURRENCY_SYMBOLS.PKR ? "PKR":"$"} ${total.toFixed(2)}`, 350, summaryY + 15);

    doc.text(`Average Expense: ${expenses[0].defaultCurrency === CURRENCY_SYMBOLS.USD ? "$":"PKR"} ${avg.toFixed(2)}`, 350, summaryY + 35);

    /* =========================
       FOOTER (FIXED POSITION)
    ========================= */

    const footerY = doc.page.height - 50;

    doc
      .fontSize(9)
      .fillColor("#888")
      .text(
        "This is an automated financial report generated by Expense Tracker System.",
        50,
        footerY,
        {
          width: 500,
          align: "center"
        }
      );

    /* =========================
       FINALIZE PDF
    ========================= */

    doc.end();

    stream.on("finish", () => {
      resolve(filePath);
    });

    stream.on("error", reject);

  });

};

module.exports = { generateMonthlyReport };

